---
- name: Converge
  hosts: all
  become: true

  vars:
    golang_binary_install:
      enable: true
      version: 1.15.8
    golang_goroot: true
    golang_gopath: /root/go

  roles:
    - ansible-role-golang
