---
- name: Converge
  hosts: all
  become: true

  vars:
    golang_binary_install:
      enable: true
      version: 1.15.8
    golang_goroot_versioned: true

  roles:
    - ansible-role-golang

  post_tasks:
    - name: Add file to GOROOT
      ansible.builtin.lineinfile:
        path: "{{ goroot }}/force_update_file"
        line: foobar
        create: yes

- name: Force Update
  hosts: all
  become: true

  vars:
    golang_binary_install:
      enable: true
      version: 1.15.8
    golang_goroot_versioned: true
    golang_force_update: true

  roles:
    - ansible-role-golang

  post_tasks:
    - name: Check if force_update_test_file Exists
      stat:
        path: "{{ goroot }}/force_update_file"
      register: force_update_file

    - name: Ensure the Update was Forced
      ansible.builtin.fail:
        msg: The update was not forced!
      when: force_update_file.stat.exists
