---
- name: Converge
  hosts: all
  become: true

  vars:
    golang_binary_install:
      enable: true
      version: 1.15.8
    golang_goroot_versioned: true

  roles:
    - ansible-role-golang

  # Place a file in the original GOPATH, which should NOT exist when the role runs a second time.
  # This is verified by verify.yml.
  post_tasks:
    - name: Add file to GOROOT
      ansible.builtin.lineinfile:
        path: "{{ goroot }}/force_update_file"
        line: foobar
        create: yes

- name: Force Update
  hosts: all
  become: true

  vars:
    golang_binary_install:
      enable: true
      version: 1.15.8
    golang_goroot_versioned: true
    golang_force_update: true

  roles:
    - ansible-role-golang
